# Generated by Django 4.2.10 on 2025-12-26 12:57

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpenseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALARY", "Salaries & Wages"),
                            ("UTILITIES", "Utilities"),
                            ("MAINTENANCE", "Maintenance & Repairs"),
                            ("SUPPLIES", "Supplies & Materials"),
                            ("EQUIPMENT", "Equipment & Technology"),
                            ("TRANSPORTATION", "Transportation"),
                            ("ADMIN", "Administrative"),
                            ("DEVELOPMENT", "Staff Development"),
                            ("BUILDING", "Building/Infrastructure"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
                ("recorded_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Expense Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="IncomeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("FEES", "Student Fees"),
                            ("DONATION", "Donation"),
                            ("GRANT", "Grant/Subsidy"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("INTEREST", "Interest Income"),
                            ("OTHER", "Other Income"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("recorded_by", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Income Records",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyFinancialSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "net_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Monthly Financial Summaries",
                "ordering": ["-month"],
                "unique_together": {("month",)},
            },
        ),
        migrations.CreateModel(
            name="CashFlowProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                (
                    "projected_income",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "projected_expenses",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "projected_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["month"],
                "unique_together": {("month",)},
            },
        ),
        migrations.CreateModel(
            name="BudgetAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SALARY", "Salaries & Wages"),
                            ("UTILITIES", "Utilities"),
                            ("MAINTENANCE", "Maintenance & Repairs"),
                            ("SUPPLIES", "Supplies & Materials"),
                            ("EQUIPMENT", "Equipment & Technology"),
                            ("TRANSPORTATION", "Transportation"),
                            ("ADMIN", "Administrative"),
                            ("DEVELOPMENT", "Staff Development"),
                            ("BUILDING", "Building/Infrastructure"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("year", models.IntegerField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-year", "category"],
                "unique_together": {("category", "year")},
            },
        ),
    ]
