# Generated by Django 4.2.10 on 2025-12-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("level", models.CharField(max_length=50)),
                ("stream", models.CharField(blank=True, max_length=50)),
                ("capacity", models.IntegerField(default=50)),
                ("year", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "class_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="classes_teaching",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Classes",
                "ordering": ["level", "name"],
                "unique_together": {("name", "year")},
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("CLASSROOM", "Classroom"),
                            ("LAB", "Laboratory"),
                            ("COMPUTER_LAB", "Computer Lab"),
                            ("LIBRARY", "Library"),
                            ("MULTI_PURPOSE", "Multi-purpose"),
                        ],
                        max_length=50,
                    ),
                ),
                ("capacity", models.IntegerField(default=50)),
                ("has_projector", models.BooleanField(default=False)),
                ("has_air_conditioning", models.BooleanField(default=False)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("NEEDS_REPAIR", "Needs Repair"),
                        ],
                        default="GOOD",
                        max_length=50,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Class Rooms",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClassPerformanceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "average_attendance_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "average_grade",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("discipline_incidents", models.IntegerField(default=0)),
                (
                    "academic_performance_trend",
                    models.CharField(
                        choices=[
                            ("IMPROVING", "Improving"),
                            ("STABLE", "Stable"),
                            ("DECLINING", "Declining"),
                        ],
                        default="STABLE",
                        max_length=50,
                    ),
                ),
                ("last_calculated", models.DateTimeField(auto_now=True)),
                (
                    "class_info",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="classes.classinfo",
                    ),
                ),
            ],
        ),
    ]
